export const bingoData = [
  "(child noises in the backgound)",
  "Hello, hello?",
  "I need to jump to another call",
  "Can everyone go on mute",
  "Could you please get closet to the mic",
  "(load painful echo/ feeback)",
  "Next slide, please",
  "Can we take this offline",
  "Is___on the cell?",
  "Could you share this slides afterwards",
  "Can somebody grant presenter rights",
  "Can you email that to everyone",
  "BINGO",
  "Sorry, I had problems loging in",
  "(animal noises in the background)",
  "Sorry, I did not find the conference id",
  "I was having connection issues",
  "I'll have to get back to you",
  "Who just joined",
  "Sorry, something with my calendar",
  "Do you see my screen",
  "Let's wait for___",
  "You will send the minutes",
  "Sorry, I was on mute",
  "Can you repeate, please"
]
